apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-computing-kubex01
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloud-computing-kubex01
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: cloud-computing-kubex01
        version: "v1"
    spec:
      containers:
        - name: cloud-computing-kub
          image: 'us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/cloud-computing-kubernate-service/cloud-computing-kubernate-service-image:v1'
          volumeMounts:
          - mountPath: /data/redis
            name: cloud-computing-kubex01-volume
          
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /Niro
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: cloud-computing-kubex01-volume
          emptyDir: {}
          
      
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-computing-kubex01
  labels:
    name: cloud-computing-kubex01
    version: "v1"
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: cloud-computing-kubex01
    version: "v1"
  type: LoadBalancer
